version: '3'
services:
  web:
    container_name: os-project
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 3000:3000
    cpu_count: 1
    mem_limit: 512m
    memswap_limit: 1g
    mem_swappiness: 0
    restart: always
