apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: argocd-app
  name: argocd-app
spec:
  replicas: 3
  selector:
    matchLabels:
      app: argocd-app
  template:
    metadata:
      labels:
        app: argocd-app
    spec:
      containers:
        - image: argocd-app
          name: argocd-app
          ports:
            - containerPort: 3000
          resources:
            limits:
              cpu: 100m
              memory: 100Mi
            requests:
              cpu: 100m
              memory: 100Mi
