apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- deployment.yml
- service.yml
namespace: os-container-project
images:
- name: os-container-project
  newName: pungrumpy/os-container-project
  newTag: 9d2fc5cd63ec1e35581df1a83fac985ffd552143
