apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- deployment.yml
- service.yml
namespace: os-container-project
images:
- name: os-container-project
  newName: pungrumpy/os-container-project
  newTag: b37342efc9cf8ed1334f5263a1090a3c1ab4ccde
