apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
metadata:
  namespace: os-container-project
resources:
- base/secret.yml
- base/elasticsearch.yml
- base/kibana.yml
- base/webserver.yml
- base/network-policy.yml
images:
- name: os-container-project
  newName: pungrumpy/os-container-project
  newTag: 0540fb023dcc526ce4b67d288466450928b685ae
