apiVersion: kustomize.config.k8s.io/v1
kind: Kustomization
resources:
- deployment.yml
- service.yml
namespace: argo-app
images:
- name: argocd-app
  newName: pungrumpy/argocd-app
  newTag: f9631384559b04441a62f5a96e9fa8ba50afaa5f
