apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- deployment.yml
- service.yml
- kafka.yml
- zookeeper.yml
namespace: os-container-project
images:
- name: kafka
  newName: wurstmeister/kafka
  newTag: 2.13-2.8.1
- name: os-container-project
  newName: pungrumpy/os-container-project
  newTag: 2472466583226ea41d17b8b8cb712195925c01d4
- name: zookeeper
  newName: zookeeper
  newTag: 3.9.1-jre-17
