apiVersion: kustomize.config.k8s.io/v1
kind: Kustomization
resources:
  - deployment.yml
  - service.yml
namespace: argo-app
images:
  - name: argo-app
    newName: pungrumpy/argo-app
    newTag: latest
