apiVersion: kustomize.config.k8s.io/v1
kind: Kustomization
resources:
- deployment.yml
- service.yml
namespace: argo-app
images:
- name: argo-app
  newName: pungrumpy/argo-app
  newTag: latest
- name: argocd-app
  newName: pungrumpy/argocd-app
  newTag: d0a85c23a6619c569b092ff84b4201b4ce2e3aa8
