apiVersion: v1
kind: Service
metadata:
  labels:
    app: argocd-app
  name: argocd-app
spec:
  ports:
    - name: http
      port: 3000
      protocol: TCP
      targetPort: 3000
  selector:
    app: argocd-app
  type: NodePort
