apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: os-container-project
  name: os-container-project
  namespace: os-container-project
spec:
  replicas: 3
  selector:
    matchLabels:
      app: os-container-project
  template:
    metadata:
      labels:
        app: os-container-project
    spec:
      containers:
        - image: os-container-project
          name: os-container-project
          ports:
            - containerPort: 3000
          resources:
            limits:
              cpu: 100m
              memory: 100Mi
            requests:
              cpu: 100m
              memory: 100Mi
          securityContext:
            runAsUser: 1000
          env:
            - name: KAFKA_URL
              value: kafka-service:9092
            - name: KAFKA_TOPIC
              value: os-container-project
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: os-container-project
  name: os-container-project
spec:
  ports:
    - name: http
      port: 3000
      protocol: TCP
      targetPort: 3000
  selector:
    app: os-container-project
  type: NodePort
