version: '3'
services:
  mariadb:
    image: mariadb:11.1.2
    container_name: mariadb
    environment:
      MYSQL_ROOT_USER: ${MARIADB_ROOT_USERNAME}
      MYSQL_ROOT_PASSWORD: ${MARIADB_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MARIADB_DATABASE}
      MYSQL_USER: ${MARIADB_USERNAME}
      MYSQL_PASSWORD: ${MARIADB_PASSWORD}
    ports:
      - ${MARIADB_PORT}:3306
    restart: unless-stopped
    volumes:
      - mariadb-data:/var/lib/mysql
    networks:
      - os-container-network
    security_opt:
      - seccomp:unconfined
  redis:
    depends_on:
      - mariadb
    image: redis:7.2.2
    container_name: redis
    command: redis-server --requirepass ${REDIS_PASSWORD}
    ports:
      - ${REDIS_PORT}:6379
    restart: unless-stopped
    networks:
      - os-container-network
  phpmyadmin:
    depends_on:
      - mariadb
    image: phpmyadmin/phpmyadmin:5.2.1
    container_name: phpmyadmin
    environment:
      PMA_HOST: mariadb
      PMA_PORT: 3306
      MYSQL_ROOT_USER: ${MARIADB_ROOT_USERNAME}
      MYSQL_ROOT_PASSWORD: ${MARIADB_ROOT_PASSWORD}
    ports:
      - ${PHPMYADMIN_PORT}:80
    restart: unless-stopped
    networks:
      - os-container-network
  redisinsight:
    depends_on:
      - redis
    image: redislabs/redisinsight:1.14.0
    container_name: redisinsight
    ports:
      - ${REDISINSIGHT_PORT}:8001
    restart: unless-stopped
    networks:
      - os-container-network
volumes:
  mariadb-data:
    name: mariadb-data
networks:
  os-container-network:
    name: os-container-network
    driver: bridge
