version: '3'
volumes:
  kafka_data:
    driver: local
networks:
  kafka-net:
    driver: bridge
services:
  zookeeper:
    image: zookeeper:3.9.1-jre-17
    container_name: zookeeper
    ports:
      - 2181:2181
    restart: always
  kafka:
    depends_on:
      - zookeeper
    image: wurstmeister/kafka:2.13-2.8.1
    container_name: kafka
    ports:
      - 9092:9092
    environment:
      KAFKA_ADVERTISED_HOST_NAME: localhost
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
