apiVersion: apps/v1
kind: StatefulSet
metadata:
  labels:
    app: elasticsearch
  name: elasticsearch
  namespace: os-container-project
spec:
  replicas: 1
  selector:
    matchLabels:
      app: elasticsearch
  serviceName: elasticsearch
  template:
    metadata:
      labels:
        app: elasticsearch
      name: elasticsearch
    spec:
      containers:
        - image: docker.elastic.co/elasticsearch/elasticsearch:7.16.0
          name: elasticsearch
          ports:
            - containerPort: 9200
          resources:
            limits:
              cpu: '1'
              memory: '512Mi'
            requests:
              cpu: '0.5'
              memory: '256Mi'
          securityContext:
            runAsUser: 1000
          env:
            - name: discovery.type
              value: 'single-node'
            - name: xpack.security.enabled
              value: 'true'
            - name: bootstrap.memory_lock
              value: 'true'
            - name: ES_JAVA_OPTS
              value: '-Xms512m -Xmx512m'
            - name: ELASTIC_USERNAME
              valueFrom:
                secretKeyRef:
                  name: elasticsearch-credentials
                  key: username
            - name: ELASTIC_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: elasticsearch-credentials
                  key: password
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: elasticsearch
  name: elasticsearch
  namespace: os-container-project
spec:
  ports:
    - name: http
      port: 9200
      protocol: TCP
      targetPort: 9200
  selector:
    app: elasticsearch
  type: ClusterIP
---
apiVersion: v1
kind: ConfigMap
metadata:
  labels:
    app: elasticsearch
  name: elasticsearch-config
  namespace: os-container-project
data:
  elasticsearch.yml: |
    cluster.name: "os-container-project"
    node.name: "os-container-project-node"
    node.attr.zone: "th"
    node.data: true
    node.master: true
    network.host: 0.0.0.0
    discovery.zen.minimum_master_nodes: 1
    http.port: 9200
    transport.tcp.port: 9300
    bootstrap.memory_lock: true
    script.allowed_types: inline
