apiVersion: v1
kind: Secret
metadata:
  labels:
    app: mariadb
  name: mariadb
type: Opaque
data:
  rootpassword: cGFzc3dvcmQ= # password
  database: bXlzcWw= # mysql
  password: cGFzc3dvcmQ= # password
  user: bXl1c2Vy # myuser
---
apiVersion: v1
kind: Secret
metadata:
  labels:
    app: redis
  name: redis
type: Opaque
data:
  password: cGFzc3dvcmQ= # password
