apiVersion: v1
kind: Secret
metadata:
  labels:
    app: elasticsearch
  name: elasticsearch-credentials
  namespace: os-container-project
type: Opaque
data:
  # Please change the username and password if you want to export elasticsearch and kibana to the internet
  username: 'ZWxhc3RpYw=='
  password: 'Y2hhbmdlbWU='
