apiVersion: apps/v1
kind: StatefulSet
metadata:
  labels:
    app: webserver
  name: webserver
  namespace: os-container-project
spec:
  replicas: 3
  selector:
    matchLabels:
      app: webserver
  serviceName: webserver
  template:
    metadata:
      labels:
        app: webserver
    spec:
      containers:
        - image: os-container-project
          name: webserver
          ports:
            - containerPort: 3000
              name: webserver
          resources:
            limits:
              cpu: '100m'
              memory: '100Mi'
            requests:
              cpu: '100m'
              memory: '100Mi'
          env:
            - name: MARIADB_HOST
              value: mariadb
            - name: MARIADB_PORT
              value: '3306'
            - name: MARIADB_USER
              valueFrom:
                secretKeyRef:
                  key: user
                  name: mariadb
            - name: MARIADB_PASSWORD
              valueFrom:
                secretKeyRef:
                  key: password
                  name: mariadb
            - name: MARIADB_DATABASE
              valueFrom:
                secretKeyRef:
                  key: database
                  name: mariadb
            - name: REDIS_HOST
              value: redis
            - name: REDIS_PORT
              value: '6379'
            - name: REDIS_PASSWORD
              valueFrom:
                secretKeyRef:
                  key: password
                  name: redis
          securityContext:
            runAsUser: 1000
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: webserver
  name: webserver
  namespace: os-container-project
spec:
  ports:
    - name: http
      port: 3000
      protocol: TCP
      targetPort: 3000
  selector:
    app: webserver
  type: NodePort
